services:
  server:
    image: cosmtrek/air
    depends_on:
      - database
    working_dir: /server
    environment:
      - DATABASE_URI=postgresql://postgres:postgres@database:5432/postgres?sslmode=disable
      - SECRET="secret key"
    ports:
      - "8080:8080"
      - "3200:3200"
    volumes:
      - ./:/server/

  database:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data/

volumes:
  db:
    driver: local
